create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  service text not null,
  master text not null,
  date date not null,
  time text not null,
  created_at timestamptz not null default now()
);

alter table public.appointments enable row level security;

create policy "Allow public inserts for appointments"
on public.appointments
for insert
to anon
with check (true);

create policy "Allow public reads for appointments"
on public.appointments
for select
to anon
using (true);
